services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    network_mode: host
    environment:
      TZ: "America/Indiana/Indianapolis"
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
      FTLCONF_webserver_port: "8080"
    volumes:
      - ./etc-pihole:/etc/pihole
    restart: unless-stopped
